// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Q6LsH8E94d4UKvWbslLuekVX8rb51m8',
    appId: '1:746326700623:web:5759f7f9938459495eb03a',
    messagingSenderId: '746326700623',
    projectId: 'to-do-list-app-d0a19',
    authDomain: 'to-do-list-app-d0a19.firebaseapp.com',
    storageBucket: 'to-do-list-app-d0a19.appspot.com',
    measurementId: 'G-XR1FGHYE7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKHac5TCHvYIAD-pDFF76njgRgXsfLBo0',
    appId: '1:746326700623:android:ad7ae0833a69a54e5eb03a',
    messagingSenderId: '746326700623',
    projectId: 'to-do-list-app-d0a19',
    storageBucket: 'to-do-list-app-d0a19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPY_YzPNjfvDlhRyrdQNLuHMiko8PGRc',
    appId: '1:746326700623:ios:80c979abd4502b745eb03a',
    messagingSenderId: '746326700623',
    projectId: 'to-do-list-app-d0a19',
    storageBucket: 'to-do-list-app-d0a19.appspot.com',
    iosClientId: '746326700623-r3e2pmuj6vha372ia9e5psa6kdta9jf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.jashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPY_YzPNjfvDlhRyrdQNLuHMiko8PGRc',
    appId: '1:746326700623:ios:3f2d959cd45de1085eb03a',
    messagingSenderId: '746326700623',
    projectId: 'to-do-list-app-d0a19',
    storageBucket: 'to-do-list-app-d0a19.appspot.com',
    iosClientId: '746326700623-htkq31p4sn2hopedqqou6mjrbav5buvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jashApp.RunnerTests',
  );
}
